name: Publish to PyPI

on: push

jobs:
  build-n-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.12.2
      uses: actions/setup-python@v3
      with:
        python-version: '3.12.2'
    - name: Install pypa/setuptools
      run: >-
        python -m
        pip install -r requirements.txt
    - name: Build a binary wheel
      run: >-
        python setup.py sdist bdist_wheel
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}